# Generated by Django 3.0.6 on 2020-05-07 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('language_code', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('description_html', models.TextField(editable=False)),
                ('code', models.TextField()),
                ('highlighted_code', models.TextField(editable=False)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('pub_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab.Language')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
